### ISSUE TITLE
Making a windows client

### ISSUE THREAD

**Issue by steskalja** [kee-org/keevault2#32]
Are there any plans to make a Windows client? You can use flutter to make a Windows client reusing the same code as your android client.

**Comment by luckyrat** [comment]
Thanks for the question.

You can reuse the same UI code (more or less) but a lot of the native integration needs to be written again for every platform. A Windows version isn't out of the question but it's not something I'm planning to work on in the short-term.

At the moment, the Kee Vault web app in a pinned tab or "installed" app works about as well as a native Windows app could. I think as platforms evolve in the coming years there will become stronger arguments to develop a version of Kee Vault 2 for desktop clients but this is a pretty broad issue so I'll close it until priorities change.
